INFO - 01-Nov-20 18:29:15 - Init started
INFO - 01-Nov-20 18:29:15 - Init finished
INFO - 01-Nov-20 18:29:15 - task has been started
INFO - 01-Nov-20 18:29:15 - create_container has been started
INFO - 01-Nov-20 18:29:15 - Request URL: 'https://bds01tro.blob.core.windows.net/trotsenkodaniil?restype=REDACTED&sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&st=REDACTED&spr=REDACTED&sig=REDACTED'
INFO - 01-Nov-20 18:29:15 - Request method: 'PUT'
INFO - 01-Nov-20 18:29:15 - Request headers:
INFO - 01-Nov-20 18:29:15 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'x-ms-date': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'x-ms-client-request-id': '61ada117-1c5f-11eb-af22-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:15 -     'User-Agent': 'azsdk-python-storage-blob/12.5.0 Python/3.8.5 (Windows-10-10.0.17763-SP0)'
INFO - 01-Nov-20 18:29:15 - No body was attached to the request
INFO - 01-Nov-20 18:29:15 - Response status: 409
INFO - 01-Nov-20 18:29:15 - Response headers:
INFO - 01-Nov-20 18:29:15 -     'Content-Length': '230'
INFO - 01-Nov-20 18:29:15 -     'Content-Type': 'application/xml'
INFO - 01-Nov-20 18:29:15 -     'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
INFO - 01-Nov-20 18:29:15 -     'x-ms-request-id': 'cc231768-201e-002a-466c-b02668000000'
INFO - 01-Nov-20 18:29:15 -     'x-ms-client-request-id': '61ada117-1c5f-11eb-af22-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:15 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'x-ms-error-code': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'Date': 'Sun, 01 Nov 2020 16:29:15 GMT'
ERROR - 01-Nov-20 18:29:15 - Exception occurred in create_container
Traceback (most recent call last):
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_container_client.py", line 280, in create_container
    return self._client.container.create( # type: ignore
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_generated\operations\_container_operations.py", line 120, in create
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The specified container already exists.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Daniil Trotsenko/Documents/Educate/Python/BDS/main.py", line 53, in task
    self.create_container()
  File "C:/Users/Daniil Trotsenko/Documents/Educate/Python/BDS/main.py", line 37, in create_container
    self.container_client = self.blob_service_client.create_container(self.container_name)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_blob_service_client.py", line 496, in create_container
    container.create_container(
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_container_client.py", line 288, in create_container
    process_storage_error(error)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified container already exists.
RequestId:cc231768-201e-002a-466c-b02668000000
Time:2020-11-01T16:29:16.2365505Z
ErrorCode:ContainerAlreadyExists
Error:None
INFO - 01-Nov-20 18:29:15 - upload_file has been started
INFO - 01-Nov-20 18:29:15 - upload_file has been finished
INFO - 01-Nov-20 18:29:15 - upload_blob has been finished
INFO - 01-Nov-20 18:29:15 - Request URL: 'https://bds01tro.blob.core.windows.net/trotsenkodaniil/IndianFoodDatasetCSV.csv?sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&st=REDACTED&spr=REDACTED&sig=REDACTED'
INFO - 01-Nov-20 18:29:15 - Request method: 'PUT'
INFO - 01-Nov-20 18:29:15 - Request headers:
INFO - 01-Nov-20 18:29:15 -     'Content-Type': 'application/octet-stream'
INFO - 01-Nov-20 18:29:15 -     'Content-Length': '24151935'
INFO - 01-Nov-20 18:29:15 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'x-ms-blob-type': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'If-None-Match': '*'
INFO - 01-Nov-20 18:29:15 -     'x-ms-date': 'REDACTED'
INFO - 01-Nov-20 18:29:15 -     'x-ms-client-request-id': '61eb7bec-1c5f-11eb-be44-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:15 -     'User-Agent': 'azsdk-python-storage-blob/12.5.0 Python/3.8.5 (Windows-10-10.0.17763-SP0)'
INFO - 01-Nov-20 18:29:15 - A body is sent with the request
INFO - 01-Nov-20 18:29:18 - Response status: 409
INFO - 01-Nov-20 18:29:18 - Response headers:
INFO - 01-Nov-20 18:29:18 -     'Content-Length': '220'
INFO - 01-Nov-20 18:29:18 -     'Content-Type': 'application/xml'
INFO - 01-Nov-20 18:29:18 -     'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
INFO - 01-Nov-20 18:29:18 -     'x-ms-request-id': 'cc231774-201e-002a-506c-b02668000000'
INFO - 01-Nov-20 18:29:18 -     'x-ms-client-request-id': '61eb7bec-1c5f-11eb-be44-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:18 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:18 -     'x-ms-error-code': 'REDACTED'
INFO - 01-Nov-20 18:29:18 -     'Date': 'Sun, 01 Nov 2020 16:29:19 GMT'
ERROR - 01-Nov-20 18:29:18 - Exception occurred in upload_blob
Traceback (most recent call last):
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_upload_helpers.py", line 95, in upload_block_blob
    return client.upload(
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_generated\operations\_block_blob_operations.py", line 222, in upload
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The specified blob already exists.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Daniil Trotsenko/Documents/Educate/Python/BDS/main.py", line 63, in task
    self.upload_blob()
  File "C:/Users/Daniil Trotsenko/Documents/Educate/Python/BDS/main.py", line 45, in upload_blob
    self.blob_client.upload_blob(data)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_upload_helpers.py", line 156, in upload_block_blob
    process_storage_error(error)
  File "C:\Users\Daniil Trotsenko\anaconda3\envs\BDS\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:cc231774-201e-002a-506c-b02668000000
Time:2020-11-01T16:29:19.6479808Z
ErrorCode:BlobAlreadyExists
Error:None
INFO - 01-Nov-20 18:29:18 - task has been finished
INFO - 01-Nov-20 18:29:18 - Request URL: 'https://bds01tro.blob.core.windows.net/?include=REDACTED&comp=REDACTED&sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&st=REDACTED&spr=REDACTED&sig=REDACTED'
INFO - 01-Nov-20 18:29:18 - Request method: 'GET'
INFO - 01-Nov-20 18:29:18 - Request headers:
INFO - 01-Nov-20 18:29:18 -     'Accept': 'application/xml'
INFO - 01-Nov-20 18:29:18 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:18 -     'x-ms-date': 'REDACTED'
INFO - 01-Nov-20 18:29:18 -     'x-ms-client-request-id': '63f234d9-1c5f-11eb-b099-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:18 -     'User-Agent': 'azsdk-python-storage-blob/12.5.0 Python/3.8.5 (Windows-10-10.0.17763-SP0)'
INFO - 01-Nov-20 18:29:18 - No body was attached to the request
INFO - 01-Nov-20 18:29:18 - Response status: 200
INFO - 01-Nov-20 18:29:18 - Response headers:
INFO - 01-Nov-20 18:29:18 -     'Transfer-Encoding': 'chunked'
INFO - 01-Nov-20 18:29:18 -     'Content-Type': 'application/xml'
INFO - 01-Nov-20 18:29:18 -     'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
INFO - 01-Nov-20 18:29:18 -     'x-ms-request-id': 'cc23194a-201e-002a-056c-b02668000000'
INFO - 01-Nov-20 18:29:18 -     'x-ms-client-request-id': '63f234d9-1c5f-11eb-b099-04d4c47a1bd8'
INFO - 01-Nov-20 18:29:18 -     'x-ms-version': 'REDACTED'
INFO - 01-Nov-20 18:29:18 -     'Date': 'Sun, 01 Nov 2020 16:29:19 GMT'
